name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Backend Build and Test
  backend:
    runs-on: ubuntu-latest
    name: Backend (Spring Boot)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        cd broker-backend
        mvn clean compile

    - name: Run tests
      run: |
        cd broker-backend
        mvn test

    - name: Package application
      run: |
        cd broker-backend
        mvn package -DskipTests

    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar
        path: broker-backend/target/*.jar
        retention-days: 7

  # Frontend Build and Test
  frontend:
    runs-on: ubuntu-latest
    name: Frontend (React/Vite)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: broker-frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd broker-frontend
        npm ci

    - name: Lint code
      run: |
        cd broker-frontend
        npm run lint

    - name: Type check
      run: |
        cd broker-frontend
        npx tsc --noEmit

    - name: Build application
      run: |
        cd broker-frontend
        npm run build

    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: broker-frontend/dist/
        retention-days: 7

  # Integration Tests (optional)
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    needs: [backend, frontend]
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-jar
        path: broker-backend/target/

    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: broker-frontend/dist/

    - name: Start backend for testing
      run: |
        cd broker-backend
        java -jar target/*.jar &
        echo $! > backend.pid
        # Wait for backend to start
        sleep 30
      timeout-minutes: 5

    - name: Run API health check
      run: |
        curl -f http://localhost:8080/actuator/health || exit 1

    - name: Stop backend
      run: |
        cd broker-backend
        if [ -f backend.pid ]; then
          kill $(cat backend.pid) || true
          rm backend.pid
        fi
